"""перестроение как надо

Revision ID: 0bf18e40b86e
Revises: d078e2598df8
Create Date: 2019-11-26 13:48:09.096879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bf18e40b86e'
down_revision = 'd078e2598df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attribute',
    sa.Column('id_attribute', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attribute_text', sa.String(length=1000), nullable=True),
    sa.Column('attribute_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id_document'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_attribute')
    )
    op.create_table('relation',
    sa.Column('id_relation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('type_relation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id_document'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_relation')
    )
    op.drop_index('ix_collection_collection_name', table_name='collection')
    op.drop_index('ix_collection_date_create', table_name='collection')
    op.drop_index('ix_collection_deadline', table_name='collection')
    op.drop_table('collection')
    op.add_column('document', sa.Column('path_to_instruction', sa.String(length=256), nullable=True))
    op.add_column('document', sa.Column('rubric', sa.String(length=140), nullable=True))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'id_collection')
    op.drop_column('document', 'id_handler')
    op.drop_column('document', 'id_loader')
    op.add_column('user', sa.Column('id_user', sa.Integer(), nullable=False))
    op.add_column('user', sa.Column('user_rating', sa.Integer(), nullable=True))
    op.drop_column('user', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('user', 'user_rating')
    op.drop_column('user', 'id_user')
    op.add_column('document', sa.Column('id_loader', sa.INTEGER(), nullable=True))
    op.add_column('document', sa.Column('id_handler', sa.INTEGER(), nullable=True))
    op.add_column('document', sa.Column('id_collection', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'document', 'collection', ['id_collection'], ['id'])
    op.create_foreign_key(None, 'document', 'user', ['id_loader'], ['id'])
    op.create_foreign_key(None, 'document', 'user', ['id_handler'], ['id'])
    op.drop_column('document', 'rubric')
    op.drop_column('document', 'path_to_instruction')
    op.create_table('collection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('id_author', sa.INTEGER(), nullable=True),
    sa.Column('id_handler', sa.INTEGER(), nullable=True),
    sa.Column('collection_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('date_create', sa.DATETIME(), nullable=True),
    sa.Column('deadline', sa.DATETIME(), nullable=True),
    sa.Column('task_description', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('template_address', sa.VARCHAR(length=256), nullable=True),
    sa.Column('annotation_address', sa.VARCHAR(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_handler'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_collection_deadline', 'collection', ['deadline'], unique=False)
    op.create_index('ix_collection_date_create', 'collection', ['date_create'], unique=False)
    op.create_index('ix_collection_collection_name', 'collection', ['collection_name'], unique=False)
    op.drop_table('relation')
    op.drop_table('attribute')
    # ### end Alembic commands ###
