"""add collection and document tables

Revision ID: d078e2598df8
Revises: 217bf6d511d5
Create Date: 2019-10-11 03:00:43.933723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd078e2598df8'
down_revision = '217bf6d511d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_author', sa.Integer(), nullable=True),
    sa.Column('id_handler', sa.Integer(), nullable=True),
    sa.Column('collection_name', sa.String(length=64), nullable=True),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('task_description', sa.String(length=1000), nullable=True),
    sa.Column('template_address', sa.String(length=256), nullable=True),
    sa.Column('annotation_address', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_handler'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_collection_name'), 'collection', ['collection_name'], unique=False)
    op.create_index(op.f('ix_collection_date_create'), 'collection', ['date_create'], unique=False)
    op.create_index(op.f('ix_collection_deadline'), 'collection', ['deadline'], unique=False)
    op.create_table('document',
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('id_collection', sa.Integer(), nullable=True),
    sa.Column('id_loader', sa.Integer(), nullable=True),
    sa.Column('id_handler', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('path_to_file', sa.String(length=256), nullable=True),
    sa.Column('path_to_xml_file', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['id_collection'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['id_handler'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id_loader'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id_document')
    )
    op.drop_index('ix_user_user_role', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_user_role', 'user', ['user_role'], unique=1)
    op.drop_table('document')
    op.drop_index(op.f('ix_collection_deadline'), table_name='collection')
    op.drop_index(op.f('ix_collection_date_create'), table_name='collection')
    op.drop_index(op.f('ix_collection_collection_name'), table_name='collection')
    op.drop_table('collection')
    # ### end Alembic commands ###
