"""empty message

Revision ID: d1be1b0798db
Revises: 68c0f5761aa4
Create Date: 2019-12-19 16:29:49.608219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1be1b0798db'
down_revision = '68c0f5761aa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_role', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_role')
    # ### end Alembic commands ###
