"""empty message

Revision ID: d98c4a836883
Revises: 
Create Date: 2019-12-18 18:28:38.383983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98c4a836883'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id_document', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.String(length=40), nullable=True),
    sa.Column('rubric', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('path_to_file', sa.String(length=256), nullable=True),
    sa.Column('path_to_xml_file', sa.String(length=256), nullable=True),
    sa.Column('path_to_instruction', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id_document')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('attribute',
    sa.Column('id_attribute', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('attribute_text', sa.String(length=1000), nullable=True),
    sa.Column('attribute_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id_document'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_attribute')
    )
    op.create_table('relation',
    sa.Column('id_relation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('type_relation', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id_document'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_relation')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('relation')
    op.drop_table('attribute')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('roles')
    op.drop_table('document')
    # ### end Alembic commands ###
